[SF-85] App WEB | Integração cadastro com API Spring
Safe-Ride/frontend pull request #17
Opened 2024-06-19 01:38 UTC by felipeguerrino-sptech

Mudanças:

* Cadastro de Motorista e Responsável 100% funcional
* Campos não-editaveis (desabilitados) são auto-completados
* Campo "Natureza Jurídica" removido

2024-06-19 16:54 UTC, brunolimabh requested changes
dei umas sugestões, e tambem seria interessante ao clicar no botão de concluir o cadastro, redirecionar pra tela de login

2024-06-19 16:54 UTC, brunolimabh commented on package.json
> +    "react-toastify": "^10.0.5",
pra que serve essa biblioteca?

2024-06-19 16:54 UTC, brunolimabh commented on src/pages/cadastro/CadastroResponsavel/Dependente/Dependente.jsx
> +      type: "datalist",
acho que poderia tirar a opção de escola.
já que iremos ter uma opção de filtro de escolas, se inserimos isso no cadastro, teriamos que mudar o layout e adicionar mais opções, então acho que seria melhor fazer isso na edição do dependente e nao no cadastro

2024-06-21 17:01 UTC, felipeguerrino-sptech commented on package.json
> +    "react-toastify": "^10.0.5",
é a biblioteca que o Bryan apresentou nos bootcamps, que dá um alerta na tela, mas não tá funcionando (não sei pq) ent vou simplesmente remover

2024-06-21 17:12 UTC, felipeguerrino-sptech commented on src/pages/cadastro/CadastroResponsavel/Dependente/Dependente.jsx
> +      type: "datalist",
![tabela dependente](https://github.com/Safe-Ride/frontend/assets/125585598/89b4f48d-0960-4971-a89c-9f9585db2e6a)

Não tem como cadastrar um dependente sem uma escola

2024-06-21 17:36 UTC, closed without merging