[SR-29] Exibição do mapa em tela cheia [SR-30] Visualização de dependente dentro do mapa
Safe-Ride/frontend pull request #42
Opened 2024-09-10 19:39 UTC by Hideki19

### Author & Jira Card
[Jira card SR-29](https://safe-ride.atlassian.net/browse/SR-29)
[Jira card SR-30](https://safe-ride.atlassian.net/browse/SR-30)
Author: @Hideki19

2024-09-10 19:40 UTC, Hideki19 commented
não sei se eu abri certo, então, qualquer coisa, eu abro 2 separados

2024-09-10 20:43 UTC, lucasrocha2704 approved these changes

2024-09-10 21:17 UTC, brunolimabh requested changes
![image](https://github.com/user-attachments/assets/ff5df9a7-0244-4419-aa16-a5540a3ecccb)

era pra funciona ou eu que tenho que fazer algo? ja deu npm i

2024-09-10 21:31 UTC, Hideki19 commented
@brunolimabh descomenta essa linha e cola o meu token no lugar do <MAPBOXACESSTOKEN>: pk.eyJ1IjoiaGlkZWtpMTkiLCJhIjoiY2x3cXcwZGx4MDZ0NDJrcTNtODlhZHYzNSJ9.XDo6sDF-eMr7z6_oFtyw8w
![image](https://github.com/user-attachments/assets/cbe91161-e55c-4f92-9cd6-f4d9bddcf8db)

2024-09-11 19:48 UTC, brunolimabh commented
@Hideki19 boa boa! funcionou!
aprovando, mas seria interessante colocar uma validação, se não tem o token ele só não exibe o mapa ao invés de dar erro

2024-09-11 19:48 UTC, brunolimabh approved these changes

2024-09-17 23:30 UTC, merged