[SR 90] Remover opção de seleção de trajetos
Safe-Ride/frontend pull request #51
Opened 2024-10-03 14:09 UTC by lucasrocha2704

2024-10-04 10:09 UTC, brunolimabh requested changes
se eu cancelar o encerramento do trajeto no modal, não consigo abrir o modal dnv.
ta certo ou tem algo de errado? @lucasrocha2704

2024-10-04 15:15 UTC, lucasrocha2704 commented
está certo sim @brunolimabh o modal só aparece perguntando se ele deseja cancelar o trajeto, quando  ele vai iniciar não tem e exibição do modal e ele volta sempre que for realizado o cancelamento do trajeto

2024-10-07 21:30 UTC, brunolimabh approved these changes

2024-10-07 21:38 UTC, felipeguerrino-sptech approved these changes

2024-10-08 20:17 UTC, merged